add ptz auto tracking
AngellusMortis/pyunifiprotect pull request #344
Opened 2024-01-18 17:44 UTC by Julian0021

The HTTP request for turning PTZ Auto Tracking simply modifies the smart detect settings of the cam.

For turning on:
  "body": "{\"smartDetectSettings\":{\"autoTrackingObjectTypes\":[\"person\"]}}",
  "method": "PATCH",

For turning off:
  "body": "{\"smartDetectSettings\":{\"autoTrackingObjectTypes\":[]}}",
  "method": "PATCH",

I dont know why its done like this, maybe they plan on enabling auto tracking on other objects than persons in the future. 
Ive added the simple functionallity to control auto track with the cli.

2024-01-18 17:48 UTC, AngellusMortis commented
There needs to be a check of whether or not the camera supports autotracking. Otherwise, there is no way to tell if a camera should have the toggle added or not.

2024-01-18 19:28 UTC, Julian0021 commented
It would suffice to check if the camera is_ptz, since only ptz cams support it.

2024-01-18 19:30 UTC, AngellusMortis commented
That looks good, but it still needs to be renamed to person tracking instead of auto-tracking. In case they add vehicle/etc. in the future.

2024-01-18 19:35 UTC, AngellusMortis commented
You can use the scripts in `.bin` to run the linters and formatters. Or just to get the commands to need to run them to make CI happy.

2024-01-20 14:51 UTC, AngellusMortis requested changes
Last thing, the new command should be added to the docs and a test added.

2024-01-21 01:22 UTC, AngellusMortis approved these changes

2024-01-21 01:22 UTC, merged